---
- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - curl
      - apt-transport-https
      - ca-certificates

- name: Crete directory for Kubernetes APT GPG key
  file:
    path: /etc/apt/keyrings
    state: directory

- name: Download and install Kubernetes APT GPG key
  ansible.builtin.shell: curl -fsSL https://dl.k8s.io/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg

- name: Add Kubernetes APT repository
  apt_repository:
    filename: kubernetes.list
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  notify: Update APT package cache

- name: Install Kubernetes packages
  apt:
      name:
      - kubeadm
      - kubelet
      - kubectl
      state: present

- name: Hold Kubernetes packages at current version
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
